apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/geekyharsh05/argocd.git'
    targetRevision: HEAD
    path: environments/production

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
