apiVersion: v1
kind: Service
metadata:
  name: nginx-production
spec:
  selector:
    app: nginx
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
